apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  app: wordpress-challenge

resources:
- ../base
- pvcs/wordpress-data.yaml
- pvcs/mariadb-data.yaml

patches:
  - path: deployments/wordpress-db_pvc_patch.yaml
  - path: deployments/wordpress_pvc_patch.yaml

secretGenerator:
  - name: mariadb-credentials
    behavior: merge
    envs:
      - secrets/mariadb.env
